### ISSUE TITLE
Add custom metrics in HTML report

### ISSUE THREAD

**Issue by nicolasbrieussel** [grafana/xk6-dashboard#102]
### Enhancement Description

Currenty (v0.6.1), there is no dashboard for the custom metrics in the html report, and since v0.6.0, the customization documentation as been removed, because the long term goal is to eliminate the need to customize it - which is great btw.

**As a result, we don't have any way to display custom metrics with a dashboard in the report**, they are only found in the summary output.

--- 

As for the reason why I propose this enhancement, it's also due to the current limitation of the k6 browser module limitation. It's also currently experimental, so some feature are missing, and the way I overcome those limitations is by adding some custom metrics. 

Even if my reasons are related to another k6 module, I think this enhancement would be usefull in many other cases (For example this [one](https://github.com/grafana/xk6-dashboard/issues/49)), make xk6-dashboard easily customizable, and still respect the long term goal. 

### Suggested Solution (optional)

Adding those custom metrics within a "Custom Metric" section. 

### Already existing or connected issues / PRs (optional)

https://github.com/grafana/xk6-dashboard/issues/49

**Comment by szkiba** [comment]
Hi @nicolasbrieussel ,
Sorry for the late answer. I've created a wiki page about customizability, hope it helps.
https://github.com/grafana/xk6-dashboard/wiki/Customization
