### ISSUE TITLE
Closing the browser tab does not close k6 after it has finished

### ISSUE THREAD

**Issue by mstoykov** [grafana/xk6-dashboard#108]
### Brief summary

Closing the browser window does not 

### k6 version

v0.46.0

### xk6-dashboard version

24d784bd2c311785ea090fb994bc9dae9ccca6bf

### OS

Linux

### Steps to reproduce the problem

start a test, click on link, look around, wait for k6 to finish and close teh tab

### Expected behaviour

The k6 instance to stop running

### Actual behaviour

k6 does not stop running at least for another 10s+ - have not measured exactly but am pretty sure I forgot it for way over 10 minutes once.

**Comment by szkiba** [comment]
Thank you for reporting this issue.
There were stability issues with the subscribe/unsubscribe feature of the underlying SSE library, which required a workaround. It seems like a good idea not to use this feature and to solve the determination of the number of active clients in a different way.

**Comment by mstoykov** [comment]
Is there a particular reason why sse is used at all?

I guess for the purposes of k6 not closing you can't just pull every 10s from the js code. But even in that case a simple websocket should be sufficient? And I would expect this will not be a problem :thinking:

**Comment by szkiba** [comment]
I solved it, now k6 will stop if there is no SSE connection (I will push it soon)
The use of SSE was quite natural for this purpose: the browser automatically reconnects when the connection is interrupted, the client automatically receives previous messages based on the last-event-id. I know it's not relevant anymore, but the SSE endpoint is potentially easier to use from an alternative UI.

**Comment by szkiba** [comment]
fixed in #110
