### ISSUE TITLE
Help link

### ISSUE THREAD

**Issue by codebien** [grafana/xk6-dashboard#117]
### Enhancement Description

The Help button currently points to the current dashboard's repo homepage. It doesn't seem optimal as the README doesn't include any specific info on how to get help.

### Suggested Solution (optional)

Point the help link to k6 [support page](https://github.com/grafana/k6/blob/master/SUPPORT.md) or [support section](https://github.com/grafana/k6#support).

I prefer the link direct to the page as it reduces the number of clicks required.

**Comment by szkiba** [comment]
Thank you for reporting this. I'll use [support page](https://github.com/grafana/k6/blob/master/SUPPORT.md) since the support section is just a link to support page.
