### ISSUE TITLE
Selected timeframe resets on next data refresh

### ISSUE THREAD

**Issue by oleiade** [grafana/xk6-dashboard#153]
### Brief summary

I have noticed that when I select a timeframe by selecting it from the panel's graph directly, my selection automatically resets on the following data refresh (currently every 10s).

Here's a gif illustrating what I mean:
![CleanShot 2024-01-22 at 11 07 55](https://github.com/grafana/xk6-dashboard/assets/690867/559390f9-355f-4065-a6fa-dfd3c35ddb9a)

I select a 1-minute timeframe from the graph, it successfully updates the view to be bound in that duration, but as soon as the data displayed are refreshed, it's reset to the original timeframe (from the beginning of the test to now).

### k6 version

v0.48.0

### xk6-dashboard version

0.7.2

### OS

MacOS

### Steps to reproduce the problem

Select a timeframe from a panel, and wait at least 10 seconds.

### Expected behaviour

The panels should keep displaying the selected timeframe?

### Actual behaviour

It resets to the timeframe from the beginning of the test to now.

**Comment by 2Steaks** [comment]
Grafana has a whole ton of logic around controlling scales and other configs. This fix could take a while.
