### ISSUE TITLE
Report charts remain empty with short test

### ISSUE THREAD

**Issue by oleiade** [grafana/xk6-dashboard#159]
### Brief summary

I ran a small test with the latest k6 build and noticed that when using the `K6_WEB_DASHBOARD_REPORT` option if a test doesn't run long enough (that's my assumption?), the report file is successfully created, but the charts appear to be empty:

**command**:
 
 ```shell
 K6_WEB_DASHBOARD=true K6_WEB_DASHBOARD_EXPORT='report.html' go run go.k6.io/k6 run ../extensions/xk6-dashboard/short-script.js
 ```

**script**:

```javascript
import http from "k6/http";

export let options = {
  iterations: 100,
};

export default function () {
  http.get("https://test-api.k6.io/");
}
```

**outcome**:
![CleanShot 2024-01-24 at 12 49 43](https://github.com/grafana/xk6-dashboard/assets/690867/062ccb78-97ea-4718-9151-e318e0a60b41)

### k6 version

master

### xk6-dashboard version

0.7.2

### OS

MacOS

### Steps to reproduce the problem

See Summary

### Expected behaviour

Best case scenario for me would be always to have some data in the report, regardless of the duration of the test. But I acknowledge there might be technical limitations to doing that. 

Otherwise, I think I would expect either the report file not to be created at all if not enough data is available. Or the report to indicate more explicitly why no data is present in some form (although I think that's not necessarily my preferred option). 

### Actual behaviour

File is created, but the charts remain empty.

**Comment by bubafinder** [comment]
Same at me, all short tests are causing empty charts.

**Comment by Madhankumar11** [comment]
ita not solved now also 
      import http from 'k6/http';
      import { sleep, check } from 'k6';
      import { randomString } from 'https://jslib.k6.io/k6-utils/1.2.0/index.js';
      import Chance from 'https://cdnjs.cloudflare.com/ajax/libs/chance/1.1.8/chance.min.js';
      const chance = new Chance();
      import { SharedArray } from 'k6/data';
      import { scenario } from 'k6/execution';

      let startTime;

      

      export const options = {
               discardResponseBodies: true,
               scenarios: {
                  contacts: {
                    executor: 'shared-iterations',
                    vus: 1,
                    iterations: 3,
                    maxDuration: '10s',
                   },
               },
             };

 

       export function setup() {
         startTime = new Date().getTime(); // store test start time
       }

      
      function request0() {
                    
          const url = 'https://dummyjson.com/todos';
          const headers = {};

          const response = http.get(url, { headers });
          check(response, { 'status is 200 or 201': (r) => r.status === 200 || r.status === 201 });
      }

      export default function () {
          const vuId = 1 + (__VU - 1);

          request0();

      }
           i am running this script for this time i am getting the empty graph  we are defining my web dashboard period is 0.2s beacuse my test was running in only 1s
