### ISSUE TITLE
xk6-dashboard no longer works as an extension

### ISSUE THREAD

**Issue by szkiba** [grafana/xk6-dashboard#162]
k6 v0.49.0 includes the xk6-dashboard extension as a built-in output extension. The name of the built-in module is the same as the output name (web-dashboard) registered by the extension. Therefore, if you try to use it as an extension (for example, a newer version), you will get the following error:

```
$ ./k6 run -o web-dashboard script.js
.
.
.
ERRO[0000] invalid output extension web-dashboard, built-in output with the same type already exists
```

**Comment by ogxd** [comment]
Same issue with `k6 run --out dashboard=export=/scenarios/report.html script.js` when using the latest docker image (`7.2.0`). Using the `0.7.3-alpha.1` version works.

**Comment by szkiba** [comment]
> Same issue with `k6 run --out dashboard=export=/scenarios/report.html script.js` when using the latest docker image (`7.2.0`). Using the `0.7.3-alpha.1` version works.

Thank you for reporting this. Yes, it is fixed on master. There is an alpha release with fix, but not released yet as normal release. It will be released soon (few weeks), until that  plz use the alpha release.
