### ISSUE TITLE
Dasboard does not display data using setup() function

### ISSUE THREAD

**Issue by EmpreLuc** [grafana/xk6-dashboard#185]
### Brief summary

When execute test with 'export default setup()' the dashboard does not shows data.

### k6 version

v0.50.0

### xk6-dashboard version

v0.7.3-alpha.1

### OS

Windows 11

### Steps to reproduce the problem

Executing with export default function setup()
![image](https://github.com/grafana/xk6-dashboard/assets/169416532/85c9966d-bb7b-4cc2-bcc4-4f0bc4c67ff5)
![image](https://github.com/grafana/xk6-dashboard/assets/169416532/c7f3e748-086b-46ab-9311-6148ed46842b)
![image](https://github.com/grafana/xk6-dashboard/assets/169416532/5cc66bae-0d6a-4fdc-a8fc-b16fbec86330)
![image](https://github.com/grafana/xk6-dashboard/assets/169416532/a380b600-d700-4481-bab4-1d681dbf9941)

Executing without export default function setup()
![image](https://github.com/grafana/xk6-dashboard/assets/169416532/f8c3b3a9-4643-4e3b-a234-767acfa197c1)
![image](https://github.com/grafana/xk6-dashboard/assets/169416532/df6b898b-cc72-4ac3-a63e-b8c9da40b0d5)
![image](https://github.com/grafana/xk6-dashboard/assets/169416532/70f06d83-e663-492b-b62e-3a1ed0c9ddfa)

### Expected behaviour

That dashboard shows data with export default function setup()

### Actual behaviour

When execute test with 'export default setup()' the dashboard does not shows data.

**Comment by EmpreLuc** [comment]
@Szkiba

**Comment by szkiba** [comment]
Hi @EmpreLuc ,

I tried to reproduce it, but it didn't work for me. Could you send me a zip file that contains everything for reproduction?
By the way, the problem is probably not the presence of the setup function (it is more complicated than that)

**Comment by EmpreLuc** [comment]
Hi @szkiba , 

**The test I tried is the next:**

`import { check } from "k6";
import http from "k6/http";

export const options = {
  "executor": "ramping-vus",
  "startVUs": 0,
  "stages": [
    { "duration": "2m", "target": 10 },
    { "duration": "5m", "target": 10 },
    { "duration": "2m", "target": 0 }
  ]
}


export function setup() {
  console.log('Example print'));
} 

export default function() {
  let res = http.get("https://test.loadimpact.com/");
  check(res, {
    "is status 200": (r) => r.status === 200
  });
};
`

[Project.zip](https://github.com/grafana/xk6-dashboard/files/15350412/Project.zip)

**xk6-dashboard builded with next command:**
xk6 build v0.51.0 --with github.com/grafana/xk6-dashboard@v0.7.3-alpha.1

**the command to execute the test:**
./k6 run -o 'web-dashboard=open=true&report=test-result.html' ./tests\restful-api\test.js

**Comment by szkiba** [comment]
Hi @EmpreLuc , Thanks for the example script. I managed to find the problem and the fix is almost complete. I will merge soon and then make a release.

**Comment by EmpreLuc** [comment]
Thank you @szkiba!
