### ISSUE TITLE
Does this support k6-operator for Kubernetes?

### ISSUE THREAD

**Issue by rutu-k** [grafana/xk6-dashboard#19]

**Comment by szkiba** [comment]
no, collecting distributed test metrics is beyond the scope of this extension

**Comment by mstoykov** [comment]
So I guess - it isn't also intended to work with any future native distributed execution in k6?

**Comment by szkiba** [comment]
There are currently no plans to support the distributed k6 environment. Since it is not yet known what API support the extensions will get in the native distributed k6 environment, it is difficult to predict whether this will change in the future.
