### ISSUE TITLE
Sparse stats graphed incorrectly?

### ISSUE THREAD

**Issue by cwilso03** [grafana/xk6-dashboard#28]
Thanks for a truly great plugin for k6!  In using it this last week, I believe there may be an error in how some of the stats are being plotted.  If you look at the attached screen shot, you can see there are 10 "humps" of activity in this increasing load test run.  But the graphs don't show the "humps" on the same time scale.  For example, in the "Generated Load" chart, the virtual user count is correct over the life of the test, ending at ~9:12 PM, but the "request rate" appears to stop at ~8:44 PM.  Similarly, the three "Load Time" charts seem to show the activity "humps" compressed in the time scale.

I'm not certain of the cause, but I believe, for the Load Time stats at least (as they are my own custom metrics being gathered), it may be because the stats are not recorded on a set interval; rather, the measured time is only recorded when all of a series of queries against the server all complete successfully.  Since, as the load increases the frequency of errors also increases, the later "humps" have fewer data points (as fewer of the request batches complete successfully).

Does the chart assume all data points for a given metric are occurring at the same time interval?

![image](https://github.com/szkiba/xk6-dashboard/assets/21103442/c0fcb1d0-423e-492c-87ba-8c75d3c30981)

**Comment by szkiba** [comment]
Thank you for reporting, I'll investigate.

**Comment by szkiba** [comment]
@cwilso03 could rerun the test, save output to compressed JSON (--out=json=results.gz) and attach it please..
Also your custom config and command line args (ie period) would be helpful.

**Comment by cwilso03** [comment]
@szkiba - will do.  It may take me a couple days before I'll be able to submit the additional info requested.

**Comment by cwilso03** [comment]
@szkiba Attached are the files requested.  For the dashboard command, I specified a period of 1 second (`1s`).

Custom dashboard config:  [config.tar.gz](https://github.com/szkiba/xk6-dashboard/files/11773065/config.tar.gz)

Test results data (JSON):  [single-server.gz](https://github.com/szkiba/xk6-dashboard/files/11772920/single-server.gz)

**Comment by szkiba** [comment]
Sorry for the delay. I'm asking for a little more patience, I'm on vacation, and then I'll start a new job. I can probably deal with the problem in mid-August.

**Comment by szkiba** [comment]
Hi @cwilso03 , Thank you for your patience. The fix is ready, I have attached the report generated from your data (in the meantime, this feature has also been completed, which can be used to save the report to a file). Version v0.5.2 contains the fix. I would be happy if you have time to confirm.
[report-28.html.gz](https://github.com/grafana/xk6-dashboard/files/12379828/report-28.html.gz)

**Comment by cwilso03** [comment]
Hi @szkiba, I can confirm the graphing looks correct now.  Thank you again!
