### ISSUE TITLE
Feature request:  ability to save and rehydrate dashboard for later interactive use

### ISSUE THREAD

**Issue by cwilso03** [grafana/xk6-dashboard#29]
Having a PDF report is great.  But it would be even better to be able to save the dashboard into some file, then later be able to rehydrate it for continued interaction in the browser.  I see it's built in React under the hood.  Any chance it could be made reloadable without requiring the test to be repeated?

**Comment by szkiba** [comment]
Maybe the replay feature what you are looking for. I just released it 2 days ago. Is it suitable for your use case?
You can save results to json and later replay it with 'k6 dashboard replay file' command.
It is not exactly same as the online version, because of json output has a hard coded 200ms aggregating period... but usually it doesn't make visible difference

**Comment by cwilso03** [comment]
From the documentation on the feature, yes, it sounds like that would work.  Unfortunately, the replay command just hangs when I run it.  The dashboard tab in the browser never appears.  Admittedly, I'm trying to load a JSON data file that is ~1 million lines long (same data file I submitted in issue #28).

**Comment by cwilso03** [comment]
Troubleshooting further, I get the following output from `k6.exe -v dashboard replay --help`:

```
ERRO[0000] unknown command "dashboard" for "k6.exe"
```

This is when running the 0.4.3 version downloaded from the Releases section.

Should I be using a different syntax for replay?

**Comment by szkiba** [comment]
Sorry for the delay. I'm asking for a little more patience, I'm on vacation, and then I'll start a new job. I can probably deal with the problem in mid-August.

**Comment by cwilso03** [comment]
No problem at all.  Thanks again for the great plugin!

**Comment by szkiba** [comment]
> From the documentation on the feature, yes, it sounds like that would work. Unfortunately, the replay command just hangs when I run it. The dashboard tab in the browser never appears. Admittedly, I'm trying to load a JSON data file that is ~1 million lines long (same data file I submitted in issue #28).

Hi @cwilso03 , which OS/platform are you use? Big JSON should not be the problem, I managed to display your file ftrom #28 .
There is a possible related issue #31  (Ubuntu 20.04)

> Troubleshooting further, I get the following output from k6.exe -v dashboard replay --help:

Oh, ye, the dashboard subcommand is a little hack, and works only if it is the first argument (just omit -v)

I guess you are using Windows...

May I ask you to check again with the latest xk6-dashboard version?
(v0.5.2)

**Comment by cwilso03** [comment]
> Hi @cwilso03 , which OS/platform are you use? Big JSON should not be the problem, I managed to display your file ftrom #28 . There is a possible related issue #31 (Ubuntu 20.04)
Yes, I'm on Windows 11.

> May I ask you to check again with the latest xk6-dashboard version? (v0.5.2)
It will likely be next week before I can check again, but yes, I'm happy to do so.

**Comment by szkiba** [comment]
> I'm on Windows 11.

I'm on Linux but I have a win 10, checked and works with your prev data file (attached to #28).

> It will likely be next week before I can check again, but yes, I'm happy to do so.

Thank you

**Comment by cwilso03** [comment]
Hi @szkiba, I can confirm the data files load correctly on replay.  Thanks again!
