### ISSUE TITLE
Is it possible to overlay the running average on a chart

### ISSUE THREAD

**Issue by jackrvan** [grafana/xk6-dashboard#30]
If I have a custom tab that contains a chart thats something like:
const customRequestChart = {
    id: 'custom_request_duration',
    title: 'Custom Request Duration (ms)',
    series: {
      'custom_request_duration_trend_avg': { label: 'avg', width: 2 },
      'custom_request_duration_trend_p(95)': { label: 'p(95)' }
    },
    axes: [{}, {}, { side: 1 }]
}
This gives me a nice chart that looks like:
![image](https://github.com/szkiba/xk6-dashboard/assets/21113205/f254bb8b-f8d0-440a-b442-9e26d2acce32)
Is there a way I can add a line that shows the running average on this chart? Right now it only shows the average of that time series. I would like to see both on the same chart.

**Comment by szkiba** [comment]
Currently it is not possible. Each chart works from different type of SSE events (either snapshot or cumulative but not both).
I'll keep it in my mind, and try to come with solution (but probably it requires some refactoring)

**Comment by szkiba** [comment]
There are currently no plans for this kind of development, so I'm closing it.
