### ISSUE TITLE
K6 Browser based load testing

### ISSUE THREAD

**Issue by crisreekoh** [grafana/xk6-dashboard#34]
I'm running a browser based testing and it seems it will not run in xk6-dashboard?

`PS C:\Users\LMPH\Projects\xk6-dashboard> K6_BROWSER_ENABLED=true ./k6 run --out dashboard BrowserScript.js
K6_BROWSER_ENABLED=true : The term 'K6_BROWSER_ENABLED=true' is not recognized as the name of a cmdlet, 
function, script file, or operable program. Check the spelling of the name, or if a path was included, 
verify that the path is correct and try again.
At line:1 char:1
+ K6_BROWSER_ENABLED=true ./k6 run --out dashboard BrowserScript.js
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (K6_BROWSER_ENABLED=true:String) [], CommandNotFoundExcep 
   tion
    + FullyQualifiedErrorId : CommandNotFoundException`

**Comment by szkiba** [comment]
Sorry for the delay. I'm asking for a little more patience, I'm on vacation, and then I'll start a new job. I can probably deal with the problem in mid-August.

**Comment by szkiba** [comment]
@crisreekoh as I see fro error message, the problem is related to your command line, not to dashboard extension....
