### ISSUE TITLE
abortOnFail in threshold doesn't end the test anymore

### ISSUE THREAD

**Issue by vkaelin** [grafana/xk6-dashboard#35]
I've added a threshold to stop my test if the `ws_connecting` time is above 200ms. It works great with k6 but I have some issue when I use your dashboard extension.

```ts
thresholds: {
    ws_connecting: [{ threshold: 'p(95)<200', abortOnFail: true }],
},
```

If I don't add the argument `--out dashboard`, my test ends with the following error message: `ERRO[0004] thresholds on metrics 'ws_connecting' were breached; at least one has abortOnFail enabled, stopping test prematurely`.

But If I set the dashboard argument, my test continue to run even if the threshold is passed. I have a little red cross close to my test name (in the stdout) but it keeps running.

What can I do to prevent this behaviour? Thanks a lot!

**Comment by vkaelin** [comment]
Looks like it's an issue with k6 directly because I have the same problem if I use `--out json=test_result.json`

**Comment by szkiba** [comment]
Sorry for the delay. I'm asking for a little more patience, I'm on vacation, and then I'll start a new job. I can probably deal with the problem in mid-August.

**Comment by szkiba** [comment]
@vkaelin as I understand it is not related to xk6-dashboard, but the k6 version. Should I close this issue?

**Comment by vkaelin** [comment]
Sorry for the late answer, yes thanks a lot!
