### ISSUE TITLE
How to run kx6 dashboard on mac?

### ISSUE THREAD

**Issue by Thanasornsawan** [grafana/xk6-dashboard#38]
I not see **### docker version for mac**.so,I try linux but it not compatible
```
MacBook-Air k6 % docker run -v $(pwd):/scripts -p 5665:5665 -it --rm ghcr.io/szkiba/xk6-dashboard:latest run --out=dashboard /scripts/script.js
Unable to find image 'ghcr.io/szkiba/xk6-dashboard:latest' locally
latest: Pulling from szkiba/xk6-dashboard
8a49fdb3b6a5: Pull complete 
307aa8d72b75: Pull complete 
dfcf9b74caa7: Pull complete 
4f4fb700ef54: Pull complete 
Digest: sha256:5d733720728489e5f75911d831a0d21d0e3eefd6c636c1333aa4718f206fbf49
Status: Downloaded newer image for ghcr.io/szkiba/xk6-dashboard:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

**### I also try command open dashboard on local. It not allow to refresh page?**
./k6 run --out 'dashboard=open=true&period=5m'  loadTestingType/simple_test.js 
It open browser and after I click reload page, the data gone.

**Comment by oleiade** [comment]
Hi @Thanasornsawan 👋🏻 

By the looks of it, the image doesn't support the `aarch64` architecture that Apple Silicon is based upon yet. 

In the meantime, I was able to address the issue by using the `--platform linux/amd64` on the `docker run` command as such:
```bash
docker run --platform linux/amd64 -v (pwd):/scripts -p 5665:5665 -it --rm ghcr.io/szkiba/xk6-dashboard:latest run /scripts/test.js
```

This instructs docker to rely on the Apple Sillicon "Rosetta" translation layer, which effectively allows Apple Sillicon to interpret x86 (amd64) instructions. I imagine this will incur a small performance impact, but it should be good enough as a temporary workaround.

Let me know if that works for you 🙇🏻

**Comment by whyparkc** [comment]
Hi @Thanasornsawan 

it looks like the `GOOS=darwin` is working when you do the `docker run`.
For me, below method worked on M2 Max Macbook.
1. Build custom k6 by using `GOOS=darwin`
  Then you will get `k6` binary file in the directory you run the docker run command.
```
$ docker run --rm -it -e GOOS=darwin -u "$(id -u):$(id -g)" -v "${PWD}:/xk6" \
  grafana/xk6 build v0.43.1 \
  --with github.com/grafana/xk6-dashboard@latest
```

2. Use the built `k6` binary for running such command like `./k6 run --out 'dashboard=open=true&period=5m' loadTestingType/simple_test.js`

That's it!

**Comment by oleiade** [comment]
Thanks a lot for your input @whyparkc 🙇🏻 
Closing this. Feel free to reopen if this issue was to reoccur in some way 👍🏻
