### ISSUE TITLE
How can i get the response time ?

### ISSUE THREAD

**Issue by HaswinVidanage** [grafana/xk6-dashboard#39]
Hi,

May I know what's the API response time metrics in K6 Dashboard? 
I cannot seem to find it here or when i run it locally.

1. https://github.com/szkiba/xk6-dashboard/blob/master/screenshot/k6-dashboard-report.pdf
2. https://github.com/szkiba/xk6-dashboard/blob/master/screenshot/k6-dashboard-timings-snapshot.png

TIA

**Comment by szkiba** [comment]
Hi @HaswinVidanage , you mean http_req_duration (HTTP request duration)? or you have a custom metrics about your API endpoint?

**Comment by szkiba** [comment]
This is the topic of "request duration" vs "response time".

Currently, k6 uses the usual name "request duration" on the dashboard. This value is also known as "response time". This is being discussed in another thread (harmonizing the names of metrics with Grafana products), so I will close it.
