### ISSUE TITLE
Communicate the dashboard's refresh-rate

### ISSUE THREAD

**Issue by oleiade** [grafana/xk6-dashboard#52]
As I started using the dashboard, I noticed that the data displayed were updated periodically. This is completely fine per se, but I've noticed that the information: "How often is the dashboard refreshed?" is not displayed on the page.

I believe displaying it, and maybe even "for how long has the test been running so far" directly in the dashboard, would be beneficial. It would help alleviate uncertainty as to whether "everything just works" in the first minutes of the test; building a clear expectation as to how often the dashboard should be refreshing.

Something along the following (I'm no UX designer, my example is ugly, and we should do something better 😉):
![Screenshot 2023-08-28 at 16 18 52 copy](https://github.com/grafana/xk6-dashboard/assets/690867/74578e30-5b6b-461e-a592-adcd1617a3e4)

I could even imagine that having a dedicated "stats box" could work for my use case 🤔

**Comment by szkiba** [comment]
Thank you, it seem good idea to show in some form (maybe a mini progress bar, or pie chart or something fancy form :)

**Comment by oleiade** [comment]
Sounds good 😸

**Comment by oleiade** [comment]
The data is available now, in the SSE events stream there is a params event, which contains the `period` parameter indicating the refresh rate in seconds.

@2Steaks can you look into this please? 🙇🏻

**Comment by 2Steaks** [comment]
What do you think? @oleiade @szkiba 

### Refresh rate / Duration
<img width="2560" alt="Screenshot 2023-11-17 at 10 08 17" src="https://github.com/grafana/xk6-dashboard/assets/4395376/987156eb-41ea-4442-9a94-cff62ea6e423">

### With Tooltip
<img width="403" alt="Screenshot 2023-11-17 at 10 08 55" src="https://github.com/grafana/xk6-dashboard/assets/4395376/b7484b0f-7bdc-4bca-a995-4c0549062e9e">
<img width="358" alt="Screenshot 2023-11-17 at 10 08 59" src="https://github.com/grafana/xk6-dashboard/assets/4395376/4f0cb85e-e92f-4424-8c1e-bd96b0514fe4">

**Comment by szkiba** [comment]
Cool, I like it!

**Comment by oleiade** [comment]
I really like it too 🎉
