### ISSUE TITLE
Test run duration is missing?

### ISSUE THREAD

**Issue by oleiade** [grafana/xk6-dashboard#53]
In the same fashion as in #52, I noticed that the test run duration (at this point) appears to be missing from the information displayed by the dashboard.

Considering the dashboard is about visualizing test results live, it would be great to have that information displayed in real-time somewhere, and if possible/available, to have the expected duration next to it for comparison. I assume that the dashboard would supersede the command-line interface, and assuming I only have the dashboard open, I wouldn't have the answer, as of today, to the question: "For how long has my test run been going on?", "How long is it gonna last?". 

Note that I might have completely missed that information, though 👍🏻 

What do you think? 🙇🏻

**Comment by szkiba** [comment]
Sure, my idea was to display a progress bar as well :)
