### ISSUE TITLE
Structuring the timings tab

### ISSUE THREAD

**Issue by oleiade** [grafana/xk6-dashboard#55]
We discussed this internally, too: the timings tab at the moment contains only HTTP information.

![Screenshot 2023-08-28 at 16 41 57](https://github.com/grafana/xk6-dashboard/assets/690867/50061436-9148-400d-a92a-a60f5f7ee11d)

My understanding is that we intend to support more metrics eventually (grpc, websockets, etc). If that's the case, I would suggest already putting the existing (HTTP) charts under a foldable HTTP subsection (in the same fashion as possible within a Grafana dashboard).

Otherwise, if we intend to keep only HTTP-related charts there, I suggest renaming the tab. 

What do you think?

**Comment by szkiba** [comment]
Sure, as we discussed there will be a foldable sections on tabs. It is on my list :)
