### ISSUE TITLE
Is it possible to add tags to tables?

### ISSUE THREAD

**Issue by gpiechnik2** [grafana/xk6-dashboard#61]
Hello, I'm wondering if it's possible to add columns with tags to a table. For example, in my test scenario, I have a counter object with a tag named "name." This tag is different depending on the request I'm making. Is it possible for me to create a table with a column called "tags" (or "tag:name") where I can filter my results? I've tried to do it, but I'm not succeeding. Hence, the question :)

**Comment by szkiba** [comment]
Currently it is not possible.

**Comment by szkiba** [comment]
There is already limited tag support in SSE events, but there are currently no plans for UI development to support this.
Although it is possible that this will change in the future.
