### ISSUE TITLE
Transfer chart display

### ISSUE THREAD

**Issue by oleiade** [grafana/xk6-dashboard#62]
As I was experimenting with Prometheus, replicating the xk6-dashboard experience, I noticed that the _Transfer Rate_ chart display feels incorrect at the moment.

The `data sent` and `data received` lines remain, in my case, very close to each other, but if I look at the respective units on the left and the right, the values differ quite a bit in reality. 

![Screenshot 2023-09-06 at 10 56 14](https://github.com/grafana/xk6-dashboard/assets/690867/9eb93440-51a4-4689-944f-102ea49119ef)

In ☝🏻, as a user I would expect the `data received` line to be 5x higher in the graph than the `data sent`. Also, in its current state, it's really hard to distinguish which value to read without hovering over it 😸 (knowing which unit scale (left or right) applies to which colored line).

Was this a design choice, or the result of a technical limitation, or should we try to address it? 🙇🏻

**Comment by szkiba** [comment]
Fortunately, it is just UI configuration

**Comment by oleiade** [comment]
What would you think of having a single unit scale and having the two lines "stacked" (I think that's how it's called in Grafana) instead? That way, I believe, the relationship would be easier to interpret 🙇🏻

**Comment by szkiba** [comment]
Yes, single unit scale sounds good idea. Why should it be "stacked"? Do we want to see sum of them? Or just simply display this 2 metrics as lines on same chart?

**Comment by oleiade** [comment]
I used the Grafana nomenclatur which turns out to be ambiguous indeed. I believe I meant to display the 2 metrics on the same chart 👍

**Comment by szkiba** [comment]
Fixed in [v0.6.0](https://github.com/grafana/xk6-dashboard/releases/tag/v0.6.0)
