### ISSUE TITLE
The html report is showing wrong iterations count

### ISSUE THREAD

**Issue by monishcorreia** [grafana/xk6-dashboard#69]
### Brief summary

1. Run your script with e.g. 20 VUs ./k6 run --vus 20 --duration 60s  --out dashboard=report=test-report.html script.js
2. Note that my mac terminal says iteration count as 834
3. whereas the html report says iteration count as 814
4. 834 - 814 = 20. The count is differing by the number of virtual users
5. If you run the script with 1 VU with 1 iteration, the report shows as blank

### k6 version

k6 v0.46.0 ((devel), go1.21.0, darwin/arm64)

### xk6-dashboard version

0.5.5

### OS

macOS 12.2

### Steps to reproduce the problem

1. Run your script with e.g. 20 VUs ./k6 run --vus 20 --duration 60s  --out dashboard=report=test-report.html script.js
2. Note that my mac terminal says iteration count as 834
3. whereas the html report says iteration count as 814
4. 834 - 814 = 20. The count is differing by the number of virtual users
5. If you run the script with 1 VU with 1 iteration, the report shows as blank

### Expected behaviour

Both the iteration count should match

### Actual behaviour

The count of iteration is lower on the html report by the number of virtual users

**Comment by monishcorreia** [comment]
![image](https://github.com/grafana/xk6-dashboard/assets/6220292/88d92792-070c-4bab-8ad8-e1cdb81e3240)
![image](https://github.com/grafana/xk6-dashboard/assets/6220292/7bba320e-8c7d-4c98-8bd7-1903400ae464)

**Comment by szkiba** [comment]
Hi @monishcorreia , In v0.6.0 release, this error was fixed. Could you please confirm that the values now correct?
