### ISSUE TITLE
Add panel summaries

### ISSUE THREAD

**Issue by szkiba** [grafana/xk6-dashboard#89]
A short summary can be added to the panels, which explains what is shown on the graph and how to interpret it. The configuration can be found in the following file:

[dashboard/assets/packages/config/src/config.js](https://github.com/grafana/xk6-dashboard/blob/master/dashboard/assets/packages/config/src/config.js)

```js
panel.summary = "<placeholder panel summary>"
```
[example placeholder](https://github.com/grafana/xk6-dashboard/blob/master/dashboard/assets/packages/config/src/config.js#L18)

This summary is displayed as a tooltip on the UI.
Currently, the text `<placeholder panel summary>` is set as a placeholder for all panels.

These placeholders should be replaced with real summaries.

**Comment by oleiade** [comment]
From a UX perspective, the panel summaries are the content displayed as we go over the circled "i" symbol in the top-left of each metric panel, as per the following screenshot.

![Screenshot 2023-11-20 at 17 17 08](https://github.com/grafana/xk6-dashboard/assets/690867/f787eebd-6d38-447d-9c03-524c0488eab9)

The user-oriented goal here is to briefly describe the actionable information a panel contains. For instance, the VUs panel description could be something along the lines of "the evolution of the number of VUs used by k6 throughout the test run", and the HTTP request duration panel's description could be something along the lines of "the evolution of the HTTP request duration is an indication of the latency experienced when making HTTP requests against the system under test".

The scope of this is different from #83, in that, as per my understanding, this is about providing helpful information as to what panel/graph contains and what information to extract from it, as opposed to (#83) obtaining the description of each metrics displayed in a panel.

I got in touch with @heitortsergent to find out if he would have the capacity to support us with that 🤞🏻
